// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Group.proto

package com.farsunset.lvxin.model.proto;

public final class GroupProto {
	private GroupProto() {
	}

	private static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {
	}

	public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
		registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
	}

	interface ModelOrBuilder extends
			// @@protoc_insertion_point(interface_extends:com.farsunset.lvxin.model.proto.Model)
			com.google.protobuf.MessageOrBuilder {

		/**
		 * <code>int64 groupId = 1;</code>
		 */
		long getGroupId();

		/**
		 * <code>string name = 2;</code>
		 */
		java.lang.String getName();

		/**
		 * <code>string name = 2;</code>
		 */
		com.google.protobuf.ByteString getNameBytes();

		/**
		 * <code>string founder = 3;</code>
		 */
		java.lang.String getFounder();

		/**
		 * <code>string founder = 3;</code>
		 */
		com.google.protobuf.ByteString getFounderBytes();

		/**
		 * <code>string category = 4;</code>
		 */
		java.lang.String getCategory();

		/**
		 * <code>string category = 4;</code>
		 */
		com.google.protobuf.ByteString getCategoryBytes();

		/**
		 * <code>string summary = 5;</code>
		 */
		java.lang.String getSummary();

		/**
		 * <code>string summary = 5;</code>
		 */
		com.google.protobuf.ByteString getSummaryBytes();
	}

	/**
	 * Protobuf type {@code com.farsunset.lvxin.model.proto.Model}
	 */
	public static final class Model extends com.google.protobuf.GeneratedMessageV3 implements
			// @@protoc_insertion_point(message_implements:com.farsunset.lvxin.model.proto.Model)
			ModelOrBuilder {
		private static final long serialVersionUID = 0L;

		// Use Model.newBuilder() to construct.
		private Model(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
			super(builder);
		}

		private Model() {
			groupId_ = 0L;
			name_ = "";
			founder_ = "";
			category_ = "";
			summary_ = "";
		}

		@java.lang.Override
		public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
			return this.unknownFields;
		}

		private Model(com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			this();
			if (extensionRegistry == null) {
				throw new java.lang.NullPointerException();
			}
			com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet
					.newBuilder();
			try {
				boolean done = false;
				while (!done) {
					int tag = input.readTag();
					switch (tag) {
					case 0:
						done = true;
						break;
					default: {
						if (!parseUnknownFieldProto3(input, unknownFields, extensionRegistry, tag)) {
							done = true;
						}
						break;
					}
					case 8: {

						groupId_ = input.readInt64();
						break;
					}
					case 18: {
						java.lang.String s = input.readStringRequireUtf8();

						name_ = s;
						break;
					}
					case 26: {
						java.lang.String s = input.readStringRequireUtf8();

						founder_ = s;
						break;
					}
					case 34: {
						java.lang.String s = input.readStringRequireUtf8();

						category_ = s;
						break;
					}
					case 42: {
						java.lang.String s = input.readStringRequireUtf8();

						summary_ = s;
						break;
					}
					}
				}
			} catch (com.google.protobuf.InvalidProtocolBufferException e) {
				throw e.setUnfinishedMessage(this);
			} catch (java.io.IOException e) {
				throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
			} finally {
				this.unknownFields = unknownFields.build();
				makeExtensionsImmutable();
			}
		}

		static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return com.farsunset.lvxin.model.proto.GroupProto.internal_static_com_farsunset_lvxin_model_proto_Model_descriptor;
		}

		protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
			return com.farsunset.lvxin.model.proto.GroupProto.internal_static_com_farsunset_lvxin_model_proto_Model_fieldAccessorTable
					.ensureFieldAccessorsInitialized(com.farsunset.lvxin.model.proto.GroupProto.Model.class,
							com.farsunset.lvxin.model.proto.GroupProto.Model.Builder.class);
		}

		static final int GROUPID_FIELD_NUMBER = 1;
		private long groupId_;

		/**
		 * <code>int64 groupId = 1;</code>
		 */
		public long getGroupId() {
			return groupId_;
		}

		static final int NAME_FIELD_NUMBER = 2;
		private volatile java.lang.Object name_;

		/**
		 * <code>string name = 2;</code>
		 */
		public java.lang.String getName() {
			java.lang.Object ref = name_;
			if (ref instanceof java.lang.String) {
				return (java.lang.String) ref;
			} else {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				java.lang.String s = bs.toStringUtf8();
				name_ = s;
				return s;
			}
		}

		/**
		 * <code>string name = 2;</code>
		 */
		public com.google.protobuf.ByteString getNameBytes() {
			java.lang.Object ref = name_;
			if (ref instanceof java.lang.String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
				name_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		static final int FOUNDER_FIELD_NUMBER = 3;
		private volatile java.lang.Object founder_;

		/**
		 * <code>string founder = 3;</code>
		 */
		public java.lang.String getFounder() {
			java.lang.Object ref = founder_;
			if (ref instanceof java.lang.String) {
				return (java.lang.String) ref;
			} else {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				java.lang.String s = bs.toStringUtf8();
				founder_ = s;
				return s;
			}
		}

		/**
		 * <code>string founder = 3;</code>
		 */
		public com.google.protobuf.ByteString getFounderBytes() {
			java.lang.Object ref = founder_;
			if (ref instanceof java.lang.String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
				founder_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		static final int CATEGORY_FIELD_NUMBER = 4;
		private volatile java.lang.Object category_;

		/**
		 * <code>string category = 4;</code>
		 */
		public java.lang.String getCategory() {
			java.lang.Object ref = category_;
			if (ref instanceof java.lang.String) {
				return (java.lang.String) ref;
			} else {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				java.lang.String s = bs.toStringUtf8();
				category_ = s;
				return s;
			}
		}

		/**
		 * <code>string category = 4;</code>
		 */
		public com.google.protobuf.ByteString getCategoryBytes() {
			java.lang.Object ref = category_;
			if (ref instanceof java.lang.String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
				category_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		static final int SUMMARY_FIELD_NUMBER = 5;
		private volatile java.lang.Object summary_;

		/**
		 * <code>string summary = 5;</code>
		 */
		public java.lang.String getSummary() {
			java.lang.Object ref = summary_;
			if (ref instanceof java.lang.String) {
				return (java.lang.String) ref;
			} else {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				java.lang.String s = bs.toStringUtf8();
				summary_ = s;
				return s;
			}
		}

		/**
		 * <code>string summary = 5;</code>
		 */
		public com.google.protobuf.ByteString getSummaryBytes() {
			java.lang.Object ref = summary_;
			if (ref instanceof java.lang.String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
				summary_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		private byte memoizedIsInitialized = -1;

		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized == 1)
				return true;
			if (isInitialized == 0)
				return false;

			memoizedIsInitialized = 1;
			return true;
		}

		public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
			if (groupId_ != 0L) {
				output.writeInt64(1, groupId_);
			}
			if (!getNameBytes().isEmpty()) {
				com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
			}
			if (!getFounderBytes().isEmpty()) {
				com.google.protobuf.GeneratedMessageV3.writeString(output, 3, founder_);
			}
			if (!getCategoryBytes().isEmpty()) {
				com.google.protobuf.GeneratedMessageV3.writeString(output, 4, category_);
			}
			if (!getSummaryBytes().isEmpty()) {
				com.google.protobuf.GeneratedMessageV3.writeString(output, 5, summary_);
			}
			unknownFields.writeTo(output);
		}

		public int getSerializedSize() {
			int size = memoizedSize;
			if (size != -1)
				return size;

			size = 0;
			if (groupId_ != 0L) {
				size += com.google.protobuf.CodedOutputStream.computeInt64Size(1, groupId_);
			}
			if (!getNameBytes().isEmpty()) {
				size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
			}
			if (!getFounderBytes().isEmpty()) {
				size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, founder_);
			}
			if (!getCategoryBytes().isEmpty()) {
				size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, category_);
			}
			if (!getSummaryBytes().isEmpty()) {
				size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, summary_);
			}
			size += unknownFields.getSerializedSize();
			memoizedSize = size;
			return size;
		}

		@java.lang.Override
		public boolean equals(final java.lang.Object obj) {
			if (obj == this) {
				return true;
			}
			if (!(obj instanceof com.farsunset.lvxin.model.proto.GroupProto.Model)) {
				return super.equals(obj);
			}
			com.farsunset.lvxin.model.proto.GroupProto.Model other = (com.farsunset.lvxin.model.proto.GroupProto.Model) obj;

			boolean result = true;
			result = result && (getGroupId() == other.getGroupId());
			result = result && getName().equals(other.getName());
			result = result && getFounder().equals(other.getFounder());
			result = result && getCategory().equals(other.getCategory());
			result = result && getSummary().equals(other.getSummary());
			result = result && unknownFields.equals(other.unknownFields);
			return result;
		}

		@java.lang.Override
		public int hashCode() {
			if (memoizedHashCode != 0) {
				return memoizedHashCode;
			}
			int hash = 41;
			hash = (19 * hash) + getDescriptor().hashCode();
			hash = (37 * hash) + GROUPID_FIELD_NUMBER;
			hash = (53 * hash) + com.google.protobuf.Internal.hashLong(getGroupId());
			hash = (37 * hash) + NAME_FIELD_NUMBER;
			hash = (53 * hash) + getName().hashCode();
			hash = (37 * hash) + FOUNDER_FIELD_NUMBER;
			hash = (53 * hash) + getFounder().hashCode();
			hash = (37 * hash) + CATEGORY_FIELD_NUMBER;
			hash = (53 * hash) + getCategory().hashCode();
			hash = (37 * hash) + SUMMARY_FIELD_NUMBER;
			hash = (53 * hash) + getSummary().hashCode();
			hash = (29 * hash) + unknownFields.hashCode();
			return hash;
		}

		public static com.farsunset.lvxin.model.proto.GroupProto.Model parseFrom(java.nio.ByteBuffer data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static com.farsunset.lvxin.model.proto.GroupProto.Model parseFrom(java.nio.ByteBuffer data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static com.farsunset.lvxin.model.proto.GroupProto.Model parseFrom(com.google.protobuf.ByteString data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static com.farsunset.lvxin.model.proto.GroupProto.Model parseFrom(com.google.protobuf.ByteString data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static com.farsunset.lvxin.model.proto.GroupProto.Model parseFrom(byte[] data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static com.farsunset.lvxin.model.proto.GroupProto.Model parseFrom(byte[] data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static com.farsunset.lvxin.model.proto.GroupProto.Model parseFrom(java.io.InputStream input)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
		}

		public static com.farsunset.lvxin.model.proto.GroupProto.Model parseFrom(java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
		}

		public static com.farsunset.lvxin.model.proto.GroupProto.Model parseDelimitedFrom(java.io.InputStream input)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
		}

		public static com.farsunset.lvxin.model.proto.GroupProto.Model parseDelimitedFrom(java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input,
					extensionRegistry);
		}

		public static com.farsunset.lvxin.model.proto.GroupProto.Model parseFrom(
				com.google.protobuf.CodedInputStream input) throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
		}

		public static com.farsunset.lvxin.model.proto.GroupProto.Model parseFrom(
				com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
		}

		public Builder newBuilderForType() {
			return newBuilder();
		}

		public static Builder newBuilder() {
			return DEFAULT_INSTANCE.toBuilder();
		}

		public static Builder newBuilder(com.farsunset.lvxin.model.proto.GroupProto.Model prototype) {
			return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
		}

		public Builder toBuilder() {
			return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
		}

		@java.lang.Override
		protected Builder newBuilderForType(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
			Builder builder = new Builder(parent);
			return builder;
		}

		/**
		 * Protobuf type {@code com.farsunset.lvxin.model.proto.Model}
		 */
		public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
				// @@protoc_insertion_point(builder_implements:com.farsunset.lvxin.model.proto.Model)
				com.farsunset.lvxin.model.proto.GroupProto.ModelOrBuilder {
			public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
				return com.farsunset.lvxin.model.proto.GroupProto.internal_static_com_farsunset_lvxin_model_proto_Model_descriptor;
			}

			protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
				return com.farsunset.lvxin.model.proto.GroupProto.internal_static_com_farsunset_lvxin_model_proto_Model_fieldAccessorTable
						.ensureFieldAccessorsInitialized(com.farsunset.lvxin.model.proto.GroupProto.Model.class,
								com.farsunset.lvxin.model.proto.GroupProto.Model.Builder.class);
			}

			// Construct using com.farsunset.lvxin.model.proto.GroupProto.Model.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
				super(parent);
				maybeForceBuilderInitialization();
			}

			private void maybeForceBuilderInitialization() {
				if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {
				}
			}

			public Builder clear() {
				super.clear();
				groupId_ = 0L;

				name_ = "";

				founder_ = "";

				category_ = "";

				summary_ = "";

				return this;
			}

			public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
				return com.farsunset.lvxin.model.proto.GroupProto.internal_static_com_farsunset_lvxin_model_proto_Model_descriptor;
			}

			public com.farsunset.lvxin.model.proto.GroupProto.Model getDefaultInstanceForType() {
				return com.farsunset.lvxin.model.proto.GroupProto.Model.getDefaultInstance();
			}

			public com.farsunset.lvxin.model.proto.GroupProto.Model build() {
				com.farsunset.lvxin.model.proto.GroupProto.Model result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			public com.farsunset.lvxin.model.proto.GroupProto.Model buildPartial() {
				com.farsunset.lvxin.model.proto.GroupProto.Model result = new com.farsunset.lvxin.model.proto.GroupProto.Model(
						this);
				result.groupId_ = groupId_;
				result.name_ = name_;
				result.founder_ = founder_;
				result.category_ = category_;
				result.summary_ = summary_;
				onBuilt();
				return result;
			}

			public Builder clone() {
				return super.clone();
			}

			public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
				return super.setField(field, value);
			}

			public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
				return super.clearField(field);
			}

			public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
				return super.clearOneof(oneof);
			}

			public Builder setRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, int index,
					java.lang.Object value) {
				return super.setRepeatedField(field, index, value);
			}

			public Builder addRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field,
					java.lang.Object value) {
				return super.addRepeatedField(field, value);
			}

			public Builder mergeFrom(com.google.protobuf.Message other) {
				if (other instanceof com.farsunset.lvxin.model.proto.GroupProto.Model) {
					return mergeFrom((com.farsunset.lvxin.model.proto.GroupProto.Model) other);
				} else {
					super.mergeFrom(other);
					return this;
				}
			}

			Builder mergeFrom(com.farsunset.lvxin.model.proto.GroupProto.Model other) {
				if (other == com.farsunset.lvxin.model.proto.GroupProto.Model.getDefaultInstance())
					return this;
				if (other.getGroupId() != 0L) {
					setGroupId(other.getGroupId());
				}
				if (!other.getName().isEmpty()) {
					name_ = other.name_;
					onChanged();
				}
				if (!other.getFounder().isEmpty()) {
					founder_ = other.founder_;
					onChanged();
				}
				if (!other.getCategory().isEmpty()) {
					category_ = other.category_;
					onChanged();
				}
				if (!other.getSummary().isEmpty()) {
					summary_ = other.summary_;
					onChanged();
				}
				this.mergeUnknownFields(other.unknownFields);
				onChanged();
				return this;
			}

			public final boolean isInitialized() {
				return true;
			}

			public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
				com.farsunset.lvxin.model.proto.GroupProto.Model parsedMessage = null;
				try {
					parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
				} catch (com.google.protobuf.InvalidProtocolBufferException e) {
					parsedMessage = (com.farsunset.lvxin.model.proto.GroupProto.Model) e.getUnfinishedMessage();
					throw e.unwrapIOException();
				} finally {
					if (parsedMessage != null) {
						mergeFrom(parsedMessage);
					}
				}
				return this;
			}

			private long groupId_;

			/**
			 * <code>int64 groupId = 1;</code>
			 */
			public long getGroupId() {
				return groupId_;
			}

			/**
			 * <code>int64 groupId = 1;</code>
			 */
			public Builder setGroupId(long value) {

				groupId_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>int64 groupId = 1;</code>
			 */
			public Builder clearGroupId() {

				groupId_ = 0L;
				onChanged();
				return this;
			}

			private java.lang.Object name_ = "";

			/**
			 * <code>string name = 2;</code>
			 */
			public java.lang.String getName() {
				java.lang.Object ref = name_;
				if (!(ref instanceof java.lang.String)) {
					com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
					java.lang.String s = bs.toStringUtf8();
					name_ = s;
					return s;
				} else {
					return (java.lang.String) ref;
				}
			}

			/**
			 * <code>string name = 2;</code>
			 */
			public com.google.protobuf.ByteString getNameBytes() {
				java.lang.Object ref = name_;
				if (ref instanceof String) {
					com.google.protobuf.ByteString b = com.google.protobuf.ByteString
							.copyFromUtf8((java.lang.String) ref);
					name_ = b;
					return b;
				} else {
					return (com.google.protobuf.ByteString) ref;
				}
			}

			/**
			 * <code>string name = 2;</code>
			 */
			public Builder setName(java.lang.String value) {
				if (value == null) {
					throw new NullPointerException();
				}

				name_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>string name = 2;</code>
			 */
			public Builder clearName() {

				name_ = getDefaultInstance().getName();
				onChanged();
				return this;
			}

			/**
			 * <code>string name = 2;</code>
			 */
			public Builder setNameBytes(com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				checkByteStringIsUtf8(value);

				name_ = value;
				onChanged();
				return this;
			}

			private java.lang.Object founder_ = "";

			/**
			 * <code>string founder = 3;</code>
			 */
			public java.lang.String getFounder() {
				java.lang.Object ref = founder_;
				if (!(ref instanceof java.lang.String)) {
					com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
					java.lang.String s = bs.toStringUtf8();
					founder_ = s;
					return s;
				} else {
					return (java.lang.String) ref;
				}
			}

			/**
			 * <code>string founder = 3;</code>
			 */
			public com.google.protobuf.ByteString getFounderBytes() {
				java.lang.Object ref = founder_;
				if (ref instanceof String) {
					com.google.protobuf.ByteString b = com.google.protobuf.ByteString
							.copyFromUtf8((java.lang.String) ref);
					founder_ = b;
					return b;
				} else {
					return (com.google.protobuf.ByteString) ref;
				}
			}

			/**
			 * <code>string founder = 3;</code>
			 */
			public Builder setFounder(java.lang.String value) {
				if (value == null) {
					throw new NullPointerException();
				}

				founder_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>string founder = 3;</code>
			 */
			public Builder clearFounder() {

				founder_ = getDefaultInstance().getFounder();
				onChanged();
				return this;
			}

			/**
			 * <code>string founder = 3;</code>
			 */
			public Builder setFounderBytes(com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				checkByteStringIsUtf8(value);

				founder_ = value;
				onChanged();
				return this;
			}

			private java.lang.Object category_ = "";

			/**
			 * <code>string category = 4;</code>
			 */
			public java.lang.String getCategory() {
				java.lang.Object ref = category_;
				if (!(ref instanceof java.lang.String)) {
					com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
					java.lang.String s = bs.toStringUtf8();
					category_ = s;
					return s;
				} else {
					return (java.lang.String) ref;
				}
			}

			/**
			 * <code>string category = 4;</code>
			 */
			public com.google.protobuf.ByteString getCategoryBytes() {
				java.lang.Object ref = category_;
				if (ref instanceof String) {
					com.google.protobuf.ByteString b = com.google.protobuf.ByteString
							.copyFromUtf8((java.lang.String) ref);
					category_ = b;
					return b;
				} else {
					return (com.google.protobuf.ByteString) ref;
				}
			}

			/**
			 * <code>string category = 4;</code>
			 */
			public Builder setCategory(java.lang.String value) {
				if (value == null) {
					throw new NullPointerException();
				}

				category_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>string category = 4;</code>
			 */
			public Builder clearCategory() {

				category_ = getDefaultInstance().getCategory();
				onChanged();
				return this;
			}

			/**
			 * <code>string category = 4;</code>
			 */
			public Builder setCategoryBytes(com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				checkByteStringIsUtf8(value);

				category_ = value;
				onChanged();
				return this;
			}

			private java.lang.Object summary_ = "";

			/**
			 * <code>string summary = 5;</code>
			 */
			public java.lang.String getSummary() {
				java.lang.Object ref = summary_;
				if (!(ref instanceof java.lang.String)) {
					com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
					java.lang.String s = bs.toStringUtf8();
					summary_ = s;
					return s;
				} else {
					return (java.lang.String) ref;
				}
			}

			/**
			 * <code>string summary = 5;</code>
			 */
			public com.google.protobuf.ByteString getSummaryBytes() {
				java.lang.Object ref = summary_;
				if (ref instanceof String) {
					com.google.protobuf.ByteString b = com.google.protobuf.ByteString
							.copyFromUtf8((java.lang.String) ref);
					summary_ = b;
					return b;
				} else {
					return (com.google.protobuf.ByteString) ref;
				}
			}

			/**
			 * <code>string summary = 5;</code>
			 */
			public Builder setSummary(java.lang.String value) {
				if (value == null) {
					throw new NullPointerException();
				}

				summary_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>string summary = 5;</code>
			 */
			public Builder clearSummary() {

				summary_ = getDefaultInstance().getSummary();
				onChanged();
				return this;
			}

			/**
			 * <code>string summary = 5;</code>
			 */
			public Builder setSummaryBytes(com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				checkByteStringIsUtf8(value);

				summary_ = value;
				onChanged();
				return this;
			}

			public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
				return super.setUnknownFieldsProto3(unknownFields);
			}

			public final Builder mergeUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
				return super.mergeUnknownFields(unknownFields);
			}

			// @@protoc_insertion_point(builder_scope:com.farsunset.lvxin.model.proto.Model)
		}

		// @@protoc_insertion_point(class_scope:com.farsunset.lvxin.model.proto.Model)
		private static final com.farsunset.lvxin.model.proto.GroupProto.Model DEFAULT_INSTANCE;
		static {
			DEFAULT_INSTANCE = new com.farsunset.lvxin.model.proto.GroupProto.Model();
		}

		static com.farsunset.lvxin.model.proto.GroupProto.Model getDefaultInstance() {
			return DEFAULT_INSTANCE;
		}

		private static final com.google.protobuf.Parser<Model> PARSER = new com.google.protobuf.AbstractParser<Model>() {
			public Model parsePartialFrom(com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws com.google.protobuf.InvalidProtocolBufferException {
				return new Model(input, extensionRegistry);
			}
		};

		public static com.google.protobuf.Parser<Model> parser() {
			return PARSER;
		}

		@java.lang.Override
		public com.google.protobuf.Parser<Model> getParserForType() {
			return PARSER;
		}

		public com.farsunset.lvxin.model.proto.GroupProto.Model getDefaultInstanceForType() {
			return DEFAULT_INSTANCE;
		}

	}

	private static final com.google.protobuf.Descriptors.Descriptor internal_static_com_farsunset_lvxin_model_proto_Model_descriptor;
	private static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_com_farsunset_lvxin_model_proto_Model_fieldAccessorTable;

	private static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
		return descriptor;
	}

	private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
	static {
		java.lang.String[] descriptorData = { "\n\013Group.proto\022\037com.farsunset.lvxin.model"
				+ ".proto\"Z\n\005Model\022\017\n\007groupId\030\001 \001(\003\022\014\n\004name"
				+ "\030\002 \001(\t\022\017\n\007founder\030\003 \001(\t\022\020\n\010category\030\004 \001("
				+ "\t\022\017\n\007summary\030\005 \001(\tB\014B\nGroupProtob\006proto3" };
		com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner = new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
			public com.google.protobuf.ExtensionRegistry assignDescriptors(
					com.google.protobuf.Descriptors.FileDescriptor root) {
				descriptor = root;
				return null;
			}
		};
		com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(descriptorData,
				new com.google.protobuf.Descriptors.FileDescriptor[] {}, assigner);
		internal_static_com_farsunset_lvxin_model_proto_Model_descriptor = getDescriptor().getMessageTypes().get(0);
		internal_static_com_farsunset_lvxin_model_proto_Model_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
				internal_static_com_farsunset_lvxin_model_proto_Model_descriptor,
				new java.lang.String[] { "GroupId", "Name", "Founder", "Category", "Summary", });
	}

	// @@protoc_insertion_point(outer_class_scope)
}
