// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: User.proto

package com.farsunset.lvxin.model.proto;

public final class UserProto {
	private UserProto() {
	}

	private static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {
	}

	public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
		registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
	}

	interface ModelOrBuilder extends
			// @@protoc_insertion_point(interface_extends:com.farsunset.lvxin.model.proto.Model)
			com.google.protobuf.MessageOrBuilder {

		/**
		 * <code>string account = 1;</code>
		 */
		java.lang.String getAccount();

		/**
		 * <code>string account = 1;</code>
		 */
		com.google.protobuf.ByteString getAccountBytes();

		/**
		 * <code>string password = 2;</code>
		 */
		java.lang.String getPassword();

		/**
		 * <code>string password = 2;</code>
		 */
		com.google.protobuf.ByteString getPasswordBytes();

		/**
		 * <code>string name = 3;</code>
		 */
		java.lang.String getName();

		/**
		 * <code>string name = 3;</code>
		 */
		com.google.protobuf.ByteString getNameBytes();

		/**
		 * <code>string telephone = 4;</code>
		 */
		java.lang.String getTelephone();

		/**
		 * <code>string telephone = 4;</code>
		 */
		com.google.protobuf.ByteString getTelephoneBytes();

		/**
		 * <code>string email = 5;</code>
		 */
		java.lang.String getEmail();

		/**
		 * <code>string email = 5;</code>
		 */
		com.google.protobuf.ByteString getEmailBytes();

		/**
		 * <code>string orgCode = 6;</code>
		 */
		java.lang.String getOrgCode();

		/**
		 * <code>string orgCode = 6;</code>
		 */
		com.google.protobuf.ByteString getOrgCodeBytes();

		/**
		 * <code>string gender = 7;</code>
		 */
		java.lang.String getGender();

		/**
		 * <code>string gender = 7;</code>
		 */
		com.google.protobuf.ByteString getGenderBytes();

		/**
		 * <code>int32 grade = 8;</code>
		 */
		int getGrade();

		/**
		 * <code>string feature = 9;</code>
		 */
		java.lang.String getFeature();

		/**
		 * <code>string feature = 9;</code>
		 */
		com.google.protobuf.ByteString getFeatureBytes();

		/**
		 * <code>string motto = 10;</code>
		 */
		java.lang.String getMotto();

		/**
		 * <code>string motto = 10;</code>
		 */
		com.google.protobuf.ByteString getMottoBytes();

		/**
		 * <code>string online = 11;</code>
		 */
		java.lang.String getOnline();

		/**
		 * <code>string online = 11;</code>
		 */
		com.google.protobuf.ByteString getOnlineBytes();

		/**
		 * <code>double longitude = 12;</code>
		 */
		double getLongitude();

		/**
		 * <code>double latitude = 13;</code>
		 */
		double getLatitude();

		/**
		 * <code>string location = 14;</code>
		 */
		java.lang.String getLocation();

		/**
		 * <code>string location = 14;</code>
		 */
		com.google.protobuf.ByteString getLocationBytes();

		/**
		 * <code>string state = 15;</code>
		 */
		java.lang.String getState();

		/**
		 * <code>string state = 15;</code>
		 */
		com.google.protobuf.ByteString getStateBytes();
	}

	/**
	 * Protobuf type {@code com.farsunset.lvxin.model.proto.Model}
	 */
	public static final class Model extends com.google.protobuf.GeneratedMessageV3 implements
			// @@protoc_insertion_point(message_implements:com.farsunset.lvxin.model.proto.Model)
			ModelOrBuilder {
		private static final long serialVersionUID = 0L;

		// Use Model.newBuilder() to construct.
		private Model(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
			super(builder);
		}

		private Model() {
			account_ = "";
			password_ = "";
			name_ = "";
			telephone_ = "";
			email_ = "";
			orgCode_ = "";
			gender_ = "";
			grade_ = 0;
			feature_ = "";
			motto_ = "";
			online_ = "";
			longitude_ = 0D;
			latitude_ = 0D;
			location_ = "";
			state_ = "";
		}

		@java.lang.Override
		public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
			return this.unknownFields;
		}

		private Model(com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			this();
			if (extensionRegistry == null) {
				throw new java.lang.NullPointerException();
			}
			// int mutable_bitField0_ = 0;
			com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet
					.newBuilder();
			try {
				boolean done = false;
				while (!done) {
					int tag = input.readTag();
					switch (tag) {
					case 0:
						done = true;
						break;
					default: {
						if (!parseUnknownFieldProto3(input, unknownFields, extensionRegistry, tag)) {
							done = true;
						}
						break;
					}
					case 10: {
						java.lang.String s = input.readStringRequireUtf8();

						account_ = s;
						break;
					}
					case 18: {
						java.lang.String s = input.readStringRequireUtf8();

						password_ = s;
						break;
					}
					case 26: {
						java.lang.String s = input.readStringRequireUtf8();

						name_ = s;
						break;
					}
					case 34: {
						java.lang.String s = input.readStringRequireUtf8();

						telephone_ = s;
						break;
					}
					case 42: {
						java.lang.String s = input.readStringRequireUtf8();

						email_ = s;
						break;
					}
					case 50: {
						java.lang.String s = input.readStringRequireUtf8();

						orgCode_ = s;
						break;
					}
					case 58: {
						java.lang.String s = input.readStringRequireUtf8();

						gender_ = s;
						break;
					}
					case 64: {

						grade_ = input.readInt32();
						break;
					}
					case 74: {
						java.lang.String s = input.readStringRequireUtf8();

						feature_ = s;
						break;
					}
					case 82: {
						java.lang.String s = input.readStringRequireUtf8();

						motto_ = s;
						break;
					}
					case 90: {
						java.lang.String s = input.readStringRequireUtf8();

						online_ = s;
						break;
					}
					case 97: {

						longitude_ = input.readDouble();
						break;
					}
					case 105: {

						latitude_ = input.readDouble();
						break;
					}
					case 114: {
						java.lang.String s = input.readStringRequireUtf8();

						location_ = s;
						break;
					}
					case 122: {
						java.lang.String s = input.readStringRequireUtf8();

						state_ = s;
						break;
					}
					}
				}
			} catch (com.google.protobuf.InvalidProtocolBufferException e) {
				throw e.setUnfinishedMessage(this);
			} catch (java.io.IOException e) {
				throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
			} finally {
				this.unknownFields = unknownFields.build();
				makeExtensionsImmutable();
			}
		}

		static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return com.farsunset.lvxin.model.proto.UserProto.internal_static_com_farsunset_lvxin_model_proto_Model_descriptor;
		}

		protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
			return com.farsunset.lvxin.model.proto.UserProto.internal_static_com_farsunset_lvxin_model_proto_Model_fieldAccessorTable
					.ensureFieldAccessorsInitialized(com.farsunset.lvxin.model.proto.UserProto.Model.class,
							com.farsunset.lvxin.model.proto.UserProto.Model.Builder.class);
		}

		static final int ACCOUNT_FIELD_NUMBER = 1;
		private volatile java.lang.Object account_;

		/**
		 * <code>string account = 1;</code>
		 */
		public java.lang.String getAccount() {
			java.lang.Object ref = account_;
			if (ref instanceof java.lang.String) {
				return (java.lang.String) ref;
			} else {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				java.lang.String s = bs.toStringUtf8();
				account_ = s;
				return s;
			}
		}

		/**
		 * <code>string account = 1;</code>
		 */
		public com.google.protobuf.ByteString getAccountBytes() {
			java.lang.Object ref = account_;
			if (ref instanceof java.lang.String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
				account_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		static final int PASSWORD_FIELD_NUMBER = 2;
		private volatile java.lang.Object password_;

		/**
		 * <code>string password = 2;</code>
		 */
		public java.lang.String getPassword() {
			java.lang.Object ref = password_;
			if (ref instanceof java.lang.String) {
				return (java.lang.String) ref;
			} else {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				java.lang.String s = bs.toStringUtf8();
				password_ = s;
				return s;
			}
		}

		/**
		 * <code>string password = 2;</code>
		 */
		public com.google.protobuf.ByteString getPasswordBytes() {
			java.lang.Object ref = password_;
			if (ref instanceof java.lang.String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
				password_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		static final int NAME_FIELD_NUMBER = 3;
		private volatile java.lang.Object name_;

		/**
		 * <code>string name = 3;</code>
		 */
		public java.lang.String getName() {
			java.lang.Object ref = name_;
			if (ref instanceof java.lang.String) {
				return (java.lang.String) ref;
			} else {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				java.lang.String s = bs.toStringUtf8();
				name_ = s;
				return s;
			}
		}

		/**
		 * <code>string name = 3;</code>
		 */
		public com.google.protobuf.ByteString getNameBytes() {
			java.lang.Object ref = name_;
			if (ref instanceof java.lang.String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
				name_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		static final int TELEPHONE_FIELD_NUMBER = 4;
		private volatile java.lang.Object telephone_;

		/**
		 * <code>string telephone = 4;</code>
		 */
		public java.lang.String getTelephone() {
			java.lang.Object ref = telephone_;
			if (ref instanceof java.lang.String) {
				return (java.lang.String) ref;
			} else {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				java.lang.String s = bs.toStringUtf8();
				telephone_ = s;
				return s;
			}
		}

		/**
		 * <code>string telephone = 4;</code>
		 */
		public com.google.protobuf.ByteString getTelephoneBytes() {
			java.lang.Object ref = telephone_;
			if (ref instanceof java.lang.String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
				telephone_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		static final int EMAIL_FIELD_NUMBER = 5;
		private volatile java.lang.Object email_;

		/**
		 * <code>string email = 5;</code>
		 */
		public java.lang.String getEmail() {
			java.lang.Object ref = email_;
			if (ref instanceof java.lang.String) {
				return (java.lang.String) ref;
			} else {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				java.lang.String s = bs.toStringUtf8();
				email_ = s;
				return s;
			}
		}

		/**
		 * <code>string email = 5;</code>
		 */
		public com.google.protobuf.ByteString getEmailBytes() {
			java.lang.Object ref = email_;
			if (ref instanceof java.lang.String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
				email_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		static final int ORGCODE_FIELD_NUMBER = 6;
		private volatile java.lang.Object orgCode_;

		/**
		 * <code>string orgCode = 6;</code>
		 */
		public java.lang.String getOrgCode() {
			java.lang.Object ref = orgCode_;
			if (ref instanceof java.lang.String) {
				return (java.lang.String) ref;
			} else {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				java.lang.String s = bs.toStringUtf8();
				orgCode_ = s;
				return s;
			}
		}

		/**
		 * <code>string orgCode = 6;</code>
		 */
		public com.google.protobuf.ByteString getOrgCodeBytes() {
			java.lang.Object ref = orgCode_;
			if (ref instanceof java.lang.String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
				orgCode_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		static final int GENDER_FIELD_NUMBER = 7;
		private volatile java.lang.Object gender_;

		/**
		 * <code>string gender = 7;</code>
		 */
		public java.lang.String getGender() {
			java.lang.Object ref = gender_;
			if (ref instanceof java.lang.String) {
				return (java.lang.String) ref;
			} else {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				java.lang.String s = bs.toStringUtf8();
				gender_ = s;
				return s;
			}
		}

		/**
		 * <code>string gender = 7;</code>
		 */
		public com.google.protobuf.ByteString getGenderBytes() {
			java.lang.Object ref = gender_;
			if (ref instanceof java.lang.String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
				gender_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		static final int GRADE_FIELD_NUMBER = 8;
		private int grade_;

		/**
		 * <code>int32 grade = 8;</code>
		 */
		public int getGrade() {
			return grade_;
		}

		static final int FEATURE_FIELD_NUMBER = 9;
		private volatile java.lang.Object feature_;

		/**
		 * <code>string feature = 9;</code>
		 */
		public java.lang.String getFeature() {
			java.lang.Object ref = feature_;
			if (ref instanceof java.lang.String) {
				return (java.lang.String) ref;
			} else {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				java.lang.String s = bs.toStringUtf8();
				feature_ = s;
				return s;
			}
		}

		/**
		 * <code>string feature = 9;</code>
		 */
		public com.google.protobuf.ByteString getFeatureBytes() {
			java.lang.Object ref = feature_;
			if (ref instanceof java.lang.String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
				feature_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		static final int MOTTO_FIELD_NUMBER = 10;
		private volatile java.lang.Object motto_;

		/**
		 * <code>string motto = 10;</code>
		 */
		public java.lang.String getMotto() {
			java.lang.Object ref = motto_;
			if (ref instanceof java.lang.String) {
				return (java.lang.String) ref;
			} else {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				java.lang.String s = bs.toStringUtf8();
				motto_ = s;
				return s;
			}
		}

		/**
		 * <code>string motto = 10;</code>
		 */
		public com.google.protobuf.ByteString getMottoBytes() {
			java.lang.Object ref = motto_;
			if (ref instanceof java.lang.String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
				motto_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		static final int ONLINE_FIELD_NUMBER = 11;
		private volatile java.lang.Object online_;

		/**
		 * <code>string online = 11;</code>
		 */
		public java.lang.String getOnline() {
			java.lang.Object ref = online_;
			if (ref instanceof java.lang.String) {
				return (java.lang.String) ref;
			} else {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				java.lang.String s = bs.toStringUtf8();
				online_ = s;
				return s;
			}
		}

		/**
		 * <code>string online = 11;</code>
		 */
		public com.google.protobuf.ByteString getOnlineBytes() {
			java.lang.Object ref = online_;
			if (ref instanceof java.lang.String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
				online_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		static final int LONGITUDE_FIELD_NUMBER = 12;
		private double longitude_;

		/**
		 * <code>double longitude = 12;</code>
		 */
		public double getLongitude() {
			return longitude_;
		}

		static final int LATITUDE_FIELD_NUMBER = 13;
		private double latitude_;

		/**
		 * <code>double latitude = 13;</code>
		 */
		public double getLatitude() {
			return latitude_;
		}

		static final int LOCATION_FIELD_NUMBER = 14;
		private volatile java.lang.Object location_;

		/**
		 * <code>string location = 14;</code>
		 */
		public java.lang.String getLocation() {
			java.lang.Object ref = location_;
			if (ref instanceof java.lang.String) {
				return (java.lang.String) ref;
			} else {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				java.lang.String s = bs.toStringUtf8();
				location_ = s;
				return s;
			}
		}

		/**
		 * <code>string location = 14;</code>
		 */
		public com.google.protobuf.ByteString getLocationBytes() {
			java.lang.Object ref = location_;
			if (ref instanceof java.lang.String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
				location_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		static final int STATE_FIELD_NUMBER = 15;
		private volatile java.lang.Object state_;

		/**
		 * <code>string state = 15;</code>
		 */
		public java.lang.String getState() {
			java.lang.Object ref = state_;
			if (ref instanceof java.lang.String) {
				return (java.lang.String) ref;
			} else {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				java.lang.String s = bs.toStringUtf8();
				state_ = s;
				return s;
			}
		}

		/**
		 * <code>string state = 15;</code>
		 */
		public com.google.protobuf.ByteString getStateBytes() {
			java.lang.Object ref = state_;
			if (ref instanceof java.lang.String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
				state_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		private byte memoizedIsInitialized = -1;

		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized == 1)
				return true;
			if (isInitialized == 0)
				return false;

			memoizedIsInitialized = 1;
			return true;
		}

		public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
			if (!getAccountBytes().isEmpty()) {
				com.google.protobuf.GeneratedMessageV3.writeString(output, 1, account_);
			}
			if (!getPasswordBytes().isEmpty()) {
				com.google.protobuf.GeneratedMessageV3.writeString(output, 2, password_);
			}
			if (!getNameBytes().isEmpty()) {
				com.google.protobuf.GeneratedMessageV3.writeString(output, 3, name_);
			}
			if (!getTelephoneBytes().isEmpty()) {
				com.google.protobuf.GeneratedMessageV3.writeString(output, 4, telephone_);
			}
			if (!getEmailBytes().isEmpty()) {
				com.google.protobuf.GeneratedMessageV3.writeString(output, 5, email_);
			}
			if (!getOrgCodeBytes().isEmpty()) {
				com.google.protobuf.GeneratedMessageV3.writeString(output, 6, orgCode_);
			}
			if (!getGenderBytes().isEmpty()) {
				com.google.protobuf.GeneratedMessageV3.writeString(output, 7, gender_);
			}
			if (grade_ != 0) {
				output.writeInt32(8, grade_);
			}
			if (!getFeatureBytes().isEmpty()) {
				com.google.protobuf.GeneratedMessageV3.writeString(output, 9, feature_);
			}
			if (!getMottoBytes().isEmpty()) {
				com.google.protobuf.GeneratedMessageV3.writeString(output, 10, motto_);
			}
			if (!getOnlineBytes().isEmpty()) {
				com.google.protobuf.GeneratedMessageV3.writeString(output, 11, online_);
			}
			if (longitude_ != 0D) {
				output.writeDouble(12, longitude_);
			}
			if (latitude_ != 0D) {
				output.writeDouble(13, latitude_);
			}
			if (!getLocationBytes().isEmpty()) {
				com.google.protobuf.GeneratedMessageV3.writeString(output, 14, location_);
			}
			if (!getStateBytes().isEmpty()) {
				com.google.protobuf.GeneratedMessageV3.writeString(output, 15, state_);
			}
			unknownFields.writeTo(output);
		}

		public int getSerializedSize() {
			int size = memoizedSize;
			if (size != -1)
				return size;

			size = 0;
			if (!getAccountBytes().isEmpty()) {
				size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, account_);
			}
			if (!getPasswordBytes().isEmpty()) {
				size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, password_);
			}
			if (!getNameBytes().isEmpty()) {
				size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, name_);
			}
			if (!getTelephoneBytes().isEmpty()) {
				size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, telephone_);
			}
			if (!getEmailBytes().isEmpty()) {
				size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, email_);
			}
			if (!getOrgCodeBytes().isEmpty()) {
				size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, orgCode_);
			}
			if (!getGenderBytes().isEmpty()) {
				size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, gender_);
			}
			if (grade_ != 0) {
				size += com.google.protobuf.CodedOutputStream.computeInt32Size(8, grade_);
			}
			if (!getFeatureBytes().isEmpty()) {
				size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, feature_);
			}
			if (!getMottoBytes().isEmpty()) {
				size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, motto_);
			}
			if (!getOnlineBytes().isEmpty()) {
				size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, online_);
			}
			if (longitude_ != 0D) {
				size += com.google.protobuf.CodedOutputStream.computeDoubleSize(12, longitude_);
			}
			if (latitude_ != 0D) {
				size += com.google.protobuf.CodedOutputStream.computeDoubleSize(13, latitude_);
			}
			if (!getLocationBytes().isEmpty()) {
				size += com.google.protobuf.GeneratedMessageV3.computeStringSize(14, location_);
			}
			if (!getStateBytes().isEmpty()) {
				size += com.google.protobuf.GeneratedMessageV3.computeStringSize(15, state_);
			}
			size += unknownFields.getSerializedSize();
			memoizedSize = size;
			return size;
		}

		@java.lang.Override
		public boolean equals(final java.lang.Object obj) {
			if (obj == this) {
				return true;
			}
			if (!(obj instanceof com.farsunset.lvxin.model.proto.UserProto.Model)) {
				return super.equals(obj);
			}
			com.farsunset.lvxin.model.proto.UserProto.Model other = (com.farsunset.lvxin.model.proto.UserProto.Model) obj;

			boolean result = true;
			result = result && getAccount().equals(other.getAccount());
			result = result && getPassword().equals(other.getPassword());
			result = result && getName().equals(other.getName());
			result = result && getTelephone().equals(other.getTelephone());
			result = result && getEmail().equals(other.getEmail());
			result = result && getOrgCode().equals(other.getOrgCode());
			result = result && getGender().equals(other.getGender());
			result = result && (getGrade() == other.getGrade());
			result = result && getFeature().equals(other.getFeature());
			result = result && getMotto().equals(other.getMotto());
			result = result && getOnline().equals(other.getOnline());
			result = result && (java.lang.Double.doubleToLongBits(getLongitude()) == java.lang.Double
					.doubleToLongBits(other.getLongitude()));
			result = result && (java.lang.Double.doubleToLongBits(getLatitude()) == java.lang.Double
					.doubleToLongBits(other.getLatitude()));
			result = result && getLocation().equals(other.getLocation());
			result = result && getState().equals(other.getState());
			result = result && unknownFields.equals(other.unknownFields);
			return result;
		}

		@SuppressWarnings("unchecked")
		@java.lang.Override
		public int hashCode() {
			if (memoizedHashCode != 0) {
				return memoizedHashCode;
			}
			int hash = 41;
			hash = (19 * hash) + getDescriptor().hashCode();
			hash = (37 * hash) + ACCOUNT_FIELD_NUMBER;
			hash = (53 * hash) + getAccount().hashCode();
			hash = (37 * hash) + PASSWORD_FIELD_NUMBER;
			hash = (53 * hash) + getPassword().hashCode();
			hash = (37 * hash) + NAME_FIELD_NUMBER;
			hash = (53 * hash) + getName().hashCode();
			hash = (37 * hash) + TELEPHONE_FIELD_NUMBER;
			hash = (53 * hash) + getTelephone().hashCode();
			hash = (37 * hash) + EMAIL_FIELD_NUMBER;
			hash = (53 * hash) + getEmail().hashCode();
			hash = (37 * hash) + ORGCODE_FIELD_NUMBER;
			hash = (53 * hash) + getOrgCode().hashCode();
			hash = (37 * hash) + GENDER_FIELD_NUMBER;
			hash = (53 * hash) + getGender().hashCode();
			hash = (37 * hash) + GRADE_FIELD_NUMBER;
			hash = (53 * hash) + getGrade();
			hash = (37 * hash) + FEATURE_FIELD_NUMBER;
			hash = (53 * hash) + getFeature().hashCode();
			hash = (37 * hash) + MOTTO_FIELD_NUMBER;
			hash = (53 * hash) + getMotto().hashCode();
			hash = (37 * hash) + ONLINE_FIELD_NUMBER;
			hash = (53 * hash) + getOnline().hashCode();
			hash = (37 * hash) + LONGITUDE_FIELD_NUMBER;
			hash = (53 * hash)
					+ com.google.protobuf.Internal.hashLong(java.lang.Double.doubleToLongBits(getLongitude()));
			hash = (37 * hash) + LATITUDE_FIELD_NUMBER;
			hash = (53 * hash)
					+ com.google.protobuf.Internal.hashLong(java.lang.Double.doubleToLongBits(getLatitude()));
			hash = (37 * hash) + LOCATION_FIELD_NUMBER;
			hash = (53 * hash) + getLocation().hashCode();
			hash = (37 * hash) + STATE_FIELD_NUMBER;
			hash = (53 * hash) + getState().hashCode();
			hash = (29 * hash) + unknownFields.hashCode();
			memoizedHashCode = hash;
			return hash;
		}

		public static com.farsunset.lvxin.model.proto.UserProto.Model parseFrom(java.nio.ByteBuffer data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static com.farsunset.lvxin.model.proto.UserProto.Model parseFrom(java.nio.ByteBuffer data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static com.farsunset.lvxin.model.proto.UserProto.Model parseFrom(com.google.protobuf.ByteString data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static com.farsunset.lvxin.model.proto.UserProto.Model parseFrom(com.google.protobuf.ByteString data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static com.farsunset.lvxin.model.proto.UserProto.Model parseFrom(byte[] data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static com.farsunset.lvxin.model.proto.UserProto.Model parseFrom(byte[] data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static com.farsunset.lvxin.model.proto.UserProto.Model parseFrom(java.io.InputStream input)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
		}

		public static com.farsunset.lvxin.model.proto.UserProto.Model parseFrom(java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
		}

		public static com.farsunset.lvxin.model.proto.UserProto.Model parseDelimitedFrom(java.io.InputStream input)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
		}

		public static com.farsunset.lvxin.model.proto.UserProto.Model parseDelimitedFrom(java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input,
					extensionRegistry);
		}

		public static com.farsunset.lvxin.model.proto.UserProto.Model parseFrom(
				com.google.protobuf.CodedInputStream input) throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
		}

		public static com.farsunset.lvxin.model.proto.UserProto.Model parseFrom(
				com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
		}

		public Builder newBuilderForType() {
			return newBuilder();
		}

		public static Builder newBuilder() {
			return DEFAULT_INSTANCE.toBuilder();
		}

		public static Builder newBuilder(com.farsunset.lvxin.model.proto.UserProto.Model prototype) {
			return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
		}

		public Builder toBuilder() {
			return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
		}

		@java.lang.Override
		protected Builder newBuilderForType(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
			Builder builder = new Builder(parent);
			return builder;
		}

		/**
		 * Protobuf type {@code com.farsunset.lvxin.model.proto.Model}
		 */
		public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
				// @@protoc_insertion_point(builder_implements:com.farsunset.lvxin.model.proto.Model)
				com.farsunset.lvxin.model.proto.UserProto.ModelOrBuilder {
			public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
				return com.farsunset.lvxin.model.proto.UserProto.internal_static_com_farsunset_lvxin_model_proto_Model_descriptor;
			}

			protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
				return com.farsunset.lvxin.model.proto.UserProto.internal_static_com_farsunset_lvxin_model_proto_Model_fieldAccessorTable
						.ensureFieldAccessorsInitialized(com.farsunset.lvxin.model.proto.UserProto.Model.class,
								com.farsunset.lvxin.model.proto.UserProto.Model.Builder.class);
			}

			// Construct using com.farsunset.lvxin.model.proto.UserProto.Model.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
				super(parent);
				maybeForceBuilderInitialization();
			}

			private void maybeForceBuilderInitialization() {
				if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {
				}
			}

			public Builder clear() {
				super.clear();
				account_ = "";

				password_ = "";

				name_ = "";

				telephone_ = "";

				email_ = "";

				orgCode_ = "";

				gender_ = "";

				grade_ = 0;

				feature_ = "";

				motto_ = "";

				online_ = "";

				longitude_ = 0D;

				latitude_ = 0D;

				location_ = "";

				state_ = "";

				return this;
			}

			public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
				return com.farsunset.lvxin.model.proto.UserProto.internal_static_com_farsunset_lvxin_model_proto_Model_descriptor;
			}

			public com.farsunset.lvxin.model.proto.UserProto.Model getDefaultInstanceForType() {
				return com.farsunset.lvxin.model.proto.UserProto.Model.getDefaultInstance();
			}

			public com.farsunset.lvxin.model.proto.UserProto.Model build() {
				com.farsunset.lvxin.model.proto.UserProto.Model result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			public com.farsunset.lvxin.model.proto.UserProto.Model buildPartial() {
				com.farsunset.lvxin.model.proto.UserProto.Model result = new com.farsunset.lvxin.model.proto.UserProto.Model(
						this);
				result.account_ = account_;
				result.password_ = password_;
				result.name_ = name_;
				result.telephone_ = telephone_;
				result.email_ = email_;
				result.orgCode_ = orgCode_;
				result.gender_ = gender_;
				result.grade_ = grade_;
				result.feature_ = feature_;
				result.motto_ = motto_;
				result.online_ = online_;
				result.longitude_ = longitude_;
				result.latitude_ = latitude_;
				result.location_ = location_;
				result.state_ = state_;
				onBuilt();
				return result;
			}

			public Builder clone() {
				return super.clone();
			}

			public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
				return super.setField(field, value);
			}

			public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
				return super.clearField(field);
			}

			public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
				return super.clearOneof(oneof);
			}

			public Builder setRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, int index,
					java.lang.Object value) {
				return super.setRepeatedField(field, index, value);
			}

			public Builder addRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field,
					java.lang.Object value) {
				return super.addRepeatedField(field, value);
			}

			public Builder mergeFrom(com.google.protobuf.Message other) {
				if (other instanceof com.farsunset.lvxin.model.proto.UserProto.Model) {
					return mergeFrom((com.farsunset.lvxin.model.proto.UserProto.Model) other);
				} else {
					super.mergeFrom(other);
					return this;
				}
			}

			Builder mergeFrom(com.farsunset.lvxin.model.proto.UserProto.Model other) {
				if (other == com.farsunset.lvxin.model.proto.UserProto.Model.getDefaultInstance())
					return this;
				if (!other.getAccount().isEmpty()) {
					account_ = other.account_;
					onChanged();
				}
				if (!other.getPassword().isEmpty()) {
					password_ = other.password_;
					onChanged();
				}
				if (!other.getName().isEmpty()) {
					name_ = other.name_;
					onChanged();
				}
				if (!other.getTelephone().isEmpty()) {
					telephone_ = other.telephone_;
					onChanged();
				}
				if (!other.getEmail().isEmpty()) {
					email_ = other.email_;
					onChanged();
				}
				if (!other.getOrgCode().isEmpty()) {
					orgCode_ = other.orgCode_;
					onChanged();
				}
				if (!other.getGender().isEmpty()) {
					gender_ = other.gender_;
					onChanged();
				}
				if (other.getGrade() != 0) {
					setGrade(other.getGrade());
				}
				if (!other.getFeature().isEmpty()) {
					feature_ = other.feature_;
					onChanged();
				}
				if (!other.getMotto().isEmpty()) {
					motto_ = other.motto_;
					onChanged();
				}
				if (!other.getOnline().isEmpty()) {
					online_ = other.online_;
					onChanged();
				}
				if (other.getLongitude() != 0D) {
					setLongitude(other.getLongitude());
				}
				if (other.getLatitude() != 0D) {
					setLatitude(other.getLatitude());
				}
				if (!other.getLocation().isEmpty()) {
					location_ = other.location_;
					onChanged();
				}
				if (!other.getState().isEmpty()) {
					state_ = other.state_;
					onChanged();
				}
				this.mergeUnknownFields(other.unknownFields);
				onChanged();
				return this;
			}

			public final boolean isInitialized() {
				return true;
			}

			public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
				com.farsunset.lvxin.model.proto.UserProto.Model parsedMessage = null;
				try {
					parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
				} catch (com.google.protobuf.InvalidProtocolBufferException e) {
					parsedMessage = (com.farsunset.lvxin.model.proto.UserProto.Model) e.getUnfinishedMessage();
					throw e.unwrapIOException();
				} finally {
					if (parsedMessage != null) {
						mergeFrom(parsedMessage);
					}
				}
				return this;
			}

			private java.lang.Object account_ = "";

			/**
			 * <code>string account = 1;</code>
			 */
			public java.lang.String getAccount() {
				java.lang.Object ref = account_;
				if (!(ref instanceof java.lang.String)) {
					com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
					java.lang.String s = bs.toStringUtf8();
					account_ = s;
					return s;
				} else {
					return (java.lang.String) ref;
				}
			}

			/**
			 * <code>string account = 1;</code>
			 */
			public com.google.protobuf.ByteString getAccountBytes() {
				java.lang.Object ref = account_;
				if (ref instanceof String) {
					com.google.protobuf.ByteString b = com.google.protobuf.ByteString
							.copyFromUtf8((java.lang.String) ref);
					account_ = b;
					return b;
				} else {
					return (com.google.protobuf.ByteString) ref;
				}
			}

			/**
			 * <code>string account = 1;</code>
			 */
			public Builder setAccount(java.lang.String value) {
				if (value == null) {
					throw new NullPointerException();
				}

				account_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>string account = 1;</code>
			 */
			public Builder clearAccount() {

				account_ = getDefaultInstance().getAccount();
				onChanged();
				return this;
			}

			/**
			 * <code>string account = 1;</code>
			 */
			public Builder setAccountBytes(com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				checkByteStringIsUtf8(value);

				account_ = value;
				onChanged();
				return this;
			}

			private java.lang.Object password_ = "";

			/**
			 * <code>string password = 2;</code>
			 */
			public java.lang.String getPassword() {
				java.lang.Object ref = password_;
				if (!(ref instanceof java.lang.String)) {
					com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
					java.lang.String s = bs.toStringUtf8();
					password_ = s;
					return s;
				} else {
					return (java.lang.String) ref;
				}
			}

			/**
			 * <code>string password = 2;</code>
			 */
			public com.google.protobuf.ByteString getPasswordBytes() {
				java.lang.Object ref = password_;
				if (ref instanceof String) {
					com.google.protobuf.ByteString b = com.google.protobuf.ByteString
							.copyFromUtf8((java.lang.String) ref);
					password_ = b;
					return b;
				} else {
					return (com.google.protobuf.ByteString) ref;
				}
			}

			/**
			 * <code>string password = 2;</code>
			 */
			public Builder setPassword(java.lang.String value) {
				if (value == null) {
					throw new NullPointerException();
				}

				password_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>string password = 2;</code>
			 */
			public Builder clearPassword() {

				password_ = getDefaultInstance().getPassword();
				onChanged();
				return this;
			}

			/**
			 * <code>string password = 2;</code>
			 */
			public Builder setPasswordBytes(com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				checkByteStringIsUtf8(value);

				password_ = value;
				onChanged();
				return this;
			}

			private java.lang.Object name_ = "";

			/**
			 * <code>string name = 3;</code>
			 */
			public java.lang.String getName() {
				java.lang.Object ref = name_;
				if (!(ref instanceof java.lang.String)) {
					com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
					java.lang.String s = bs.toStringUtf8();
					name_ = s;
					return s;
				} else {
					return (java.lang.String) ref;
				}
			}

			/**
			 * <code>string name = 3;</code>
			 */
			public com.google.protobuf.ByteString getNameBytes() {
				java.lang.Object ref = name_;
				if (ref instanceof String) {
					com.google.protobuf.ByteString b = com.google.protobuf.ByteString
							.copyFromUtf8((java.lang.String) ref);
					name_ = b;
					return b;
				} else {
					return (com.google.protobuf.ByteString) ref;
				}
			}

			/**
			 * <code>string name = 3;</code>
			 */
			public Builder setName(java.lang.String value) {
				if (value == null) {
					throw new NullPointerException();
				}

				name_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>string name = 3;</code>
			 */
			public Builder clearName() {

				name_ = getDefaultInstance().getName();
				onChanged();
				return this;
			}

			/**
			 * <code>string name = 3;</code>
			 */
			public Builder setNameBytes(com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				checkByteStringIsUtf8(value);

				name_ = value;
				onChanged();
				return this;
			}

			private java.lang.Object telephone_ = "";

			/**
			 * <code>string telephone = 4;</code>
			 */
			public java.lang.String getTelephone() {
				java.lang.Object ref = telephone_;
				if (!(ref instanceof java.lang.String)) {
					com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
					java.lang.String s = bs.toStringUtf8();
					telephone_ = s;
					return s;
				} else {
					return (java.lang.String) ref;
				}
			}

			/**
			 * <code>string telephone = 4;</code>
			 */
			public com.google.protobuf.ByteString getTelephoneBytes() {
				java.lang.Object ref = telephone_;
				if (ref instanceof String) {
					com.google.protobuf.ByteString b = com.google.protobuf.ByteString
							.copyFromUtf8((java.lang.String) ref);
					telephone_ = b;
					return b;
				} else {
					return (com.google.protobuf.ByteString) ref;
				}
			}

			/**
			 * <code>string telephone = 4;</code>
			 */
			public Builder setTelephone(java.lang.String value) {
				if (value == null) {
					throw new NullPointerException();
				}

				telephone_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>string telephone = 4;</code>
			 */
			public Builder clearTelephone() {

				telephone_ = getDefaultInstance().getTelephone();
				onChanged();
				return this;
			}

			/**
			 * <code>string telephone = 4;</code>
			 */
			public Builder setTelephoneBytes(com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				checkByteStringIsUtf8(value);

				telephone_ = value;
				onChanged();
				return this;
			}

			private java.lang.Object email_ = "";

			/**
			 * <code>string email = 5;</code>
			 */
			public java.lang.String getEmail() {
				java.lang.Object ref = email_;
				if (!(ref instanceof java.lang.String)) {
					com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
					java.lang.String s = bs.toStringUtf8();
					email_ = s;
					return s;
				} else {
					return (java.lang.String) ref;
				}
			}

			/**
			 * <code>string email = 5;</code>
			 */
			public com.google.protobuf.ByteString getEmailBytes() {
				java.lang.Object ref = email_;
				if (ref instanceof String) {
					com.google.protobuf.ByteString b = com.google.protobuf.ByteString
							.copyFromUtf8((java.lang.String) ref);
					email_ = b;
					return b;
				} else {
					return (com.google.protobuf.ByteString) ref;
				}
			}

			/**
			 * <code>string email = 5;</code>
			 */
			public Builder setEmail(java.lang.String value) {
				if (value == null) {
					throw new NullPointerException();
				}

				email_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>string email = 5;</code>
			 */
			public Builder clearEmail() {

				email_ = getDefaultInstance().getEmail();
				onChanged();
				return this;
			}

			/**
			 * <code>string email = 5;</code>
			 */
			public Builder setEmailBytes(com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				checkByteStringIsUtf8(value);

				email_ = value;
				onChanged();
				return this;
			}

			private java.lang.Object orgCode_ = "";

			/**
			 * <code>string orgCode = 6;</code>
			 */
			public java.lang.String getOrgCode() {
				java.lang.Object ref = orgCode_;
				if (!(ref instanceof java.lang.String)) {
					com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
					java.lang.String s = bs.toStringUtf8();
					orgCode_ = s;
					return s;
				} else {
					return (java.lang.String) ref;
				}
			}

			/**
			 * <code>string orgCode = 6;</code>
			 */
			public com.google.protobuf.ByteString getOrgCodeBytes() {
				java.lang.Object ref = orgCode_;
				if (ref instanceof String) {
					com.google.protobuf.ByteString b = com.google.protobuf.ByteString
							.copyFromUtf8((java.lang.String) ref);
					orgCode_ = b;
					return b;
				} else {
					return (com.google.protobuf.ByteString) ref;
				}
			}

			/**
			 * <code>string orgCode = 6;</code>
			 */
			public Builder setOrgCode(java.lang.String value) {
				if (value == null) {
					throw new NullPointerException();
				}

				orgCode_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>string orgCode = 6;</code>
			 */
			public Builder clearOrgCode() {

				orgCode_ = getDefaultInstance().getOrgCode();
				onChanged();
				return this;
			}

			/**
			 * <code>string orgCode = 6;</code>
			 */
			public Builder setOrgCodeBytes(com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				checkByteStringIsUtf8(value);

				orgCode_ = value;
				onChanged();
				return this;
			}

			private java.lang.Object gender_ = "";

			/**
			 * <code>string gender = 7;</code>
			 */
			public java.lang.String getGender() {
				java.lang.Object ref = gender_;
				if (!(ref instanceof java.lang.String)) {
					com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
					java.lang.String s = bs.toStringUtf8();
					gender_ = s;
					return s;
				} else {
					return (java.lang.String) ref;
				}
			}

			/**
			 * <code>string gender = 7;</code>
			 */
			public com.google.protobuf.ByteString getGenderBytes() {
				java.lang.Object ref = gender_;
				if (ref instanceof String) {
					com.google.protobuf.ByteString b = com.google.protobuf.ByteString
							.copyFromUtf8((java.lang.String) ref);
					gender_ = b;
					return b;
				} else {
					return (com.google.protobuf.ByteString) ref;
				}
			}

			/**
			 * <code>string gender = 7;</code>
			 */
			public Builder setGender(java.lang.String value) {
				if (value == null) {
					throw new NullPointerException();
				}

				gender_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>string gender = 7;</code>
			 */
			public Builder clearGender() {

				gender_ = getDefaultInstance().getGender();
				onChanged();
				return this;
			}

			/**
			 * <code>string gender = 7;</code>
			 */
			public Builder setGenderBytes(com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				checkByteStringIsUtf8(value);

				gender_ = value;
				onChanged();
				return this;
			}

			private int grade_;

			/**
			 * <code>int32 grade = 8;</code>
			 */
			public int getGrade() {
				return grade_;
			}

			/**
			 * <code>int32 grade = 8;</code>
			 */
			public Builder setGrade(int value) {

				grade_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>int32 grade = 8;</code>
			 */
			public Builder clearGrade() {

				grade_ = 0;
				onChanged();
				return this;
			}

			private java.lang.Object feature_ = "";

			/**
			 * <code>string feature = 9;</code>
			 */
			public java.lang.String getFeature() {
				java.lang.Object ref = feature_;
				if (!(ref instanceof java.lang.String)) {
					com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
					java.lang.String s = bs.toStringUtf8();
					feature_ = s;
					return s;
				} else {
					return (java.lang.String) ref;
				}
			}

			/**
			 * <code>string feature = 9;</code>
			 */
			public com.google.protobuf.ByteString getFeatureBytes() {
				java.lang.Object ref = feature_;
				if (ref instanceof String) {
					com.google.protobuf.ByteString b = com.google.protobuf.ByteString
							.copyFromUtf8((java.lang.String) ref);
					feature_ = b;
					return b;
				} else {
					return (com.google.protobuf.ByteString) ref;
				}
			}

			/**
			 * <code>string feature = 9;</code>
			 */
			public Builder setFeature(java.lang.String value) {
				if (value == null) {
					throw new NullPointerException();
				}

				feature_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>string feature = 9;</code>
			 */
			public Builder clearFeature() {

				feature_ = getDefaultInstance().getFeature();
				onChanged();
				return this;
			}

			/**
			 * <code>string feature = 9;</code>
			 */
			public Builder setFeatureBytes(com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				checkByteStringIsUtf8(value);

				feature_ = value;
				onChanged();
				return this;
			}

			private java.lang.Object motto_ = "";

			/**
			 * <code>string motto = 10;</code>
			 */
			public java.lang.String getMotto() {
				java.lang.Object ref = motto_;
				if (!(ref instanceof java.lang.String)) {
					com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
					java.lang.String s = bs.toStringUtf8();
					motto_ = s;
					return s;
				} else {
					return (java.lang.String) ref;
				}
			}

			/**
			 * <code>string motto = 10;</code>
			 */
			public com.google.protobuf.ByteString getMottoBytes() {
				java.lang.Object ref = motto_;
				if (ref instanceof String) {
					com.google.protobuf.ByteString b = com.google.protobuf.ByteString
							.copyFromUtf8((java.lang.String) ref);
					motto_ = b;
					return b;
				} else {
					return (com.google.protobuf.ByteString) ref;
				}
			}

			/**
			 * <code>string motto = 10;</code>
			 */
			public Builder setMotto(java.lang.String value) {
				if (value == null) {
					throw new NullPointerException();
				}

				motto_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>string motto = 10;</code>
			 */
			public Builder clearMotto() {

				motto_ = getDefaultInstance().getMotto();
				onChanged();
				return this;
			}

			/**
			 * <code>string motto = 10;</code>
			 */
			public Builder setMottoBytes(com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				checkByteStringIsUtf8(value);

				motto_ = value;
				onChanged();
				return this;
			}

			private java.lang.Object online_ = "";

			/**
			 * <code>string online = 11;</code>
			 */
			public java.lang.String getOnline() {
				java.lang.Object ref = online_;
				if (!(ref instanceof java.lang.String)) {
					com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
					java.lang.String s = bs.toStringUtf8();
					online_ = s;
					return s;
				} else {
					return (java.lang.String) ref;
				}
			}

			/**
			 * <code>string online = 11;</code>
			 */
			public com.google.protobuf.ByteString getOnlineBytes() {
				java.lang.Object ref = online_;
				if (ref instanceof String) {
					com.google.protobuf.ByteString b = com.google.protobuf.ByteString
							.copyFromUtf8((java.lang.String) ref);
					online_ = b;
					return b;
				} else {
					return (com.google.protobuf.ByteString) ref;
				}
			}

			/**
			 * <code>string online = 11;</code>
			 */
			public Builder setOnline(java.lang.String value) {
				if (value == null) {
					throw new NullPointerException();
				}

				online_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>string online = 11;</code>
			 */
			public Builder clearOnline() {

				online_ = getDefaultInstance().getOnline();
				onChanged();
				return this;
			}

			/**
			 * <code>string online = 11;</code>
			 */
			public Builder setOnlineBytes(com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				checkByteStringIsUtf8(value);

				online_ = value;
				onChanged();
				return this;
			}

			private double longitude_;

			/**
			 * <code>double longitude = 12;</code>
			 */
			public double getLongitude() {
				return longitude_;
			}

			/**
			 * <code>double longitude = 12;</code>
			 */
			public Builder setLongitude(double value) {

				longitude_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>double longitude = 12;</code>
			 */
			public Builder clearLongitude() {

				longitude_ = 0D;
				onChanged();
				return this;
			}

			private double latitude_;

			/**
			 * <code>double latitude = 13;</code>
			 */
			public double getLatitude() {
				return latitude_;
			}

			/**
			 * <code>double latitude = 13;</code>
			 */
			public Builder setLatitude(double value) {

				latitude_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>double latitude = 13;</code>
			 */
			public Builder clearLatitude() {

				latitude_ = 0D;
				onChanged();
				return this;
			}

			private java.lang.Object location_ = "";

			/**
			 * <code>string location = 14;</code>
			 */
			public java.lang.String getLocation() {
				java.lang.Object ref = location_;
				if (!(ref instanceof java.lang.String)) {
					com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
					java.lang.String s = bs.toStringUtf8();
					location_ = s;
					return s;
				} else {
					return (java.lang.String) ref;
				}
			}

			/**
			 * <code>string location = 14;</code>
			 */
			public com.google.protobuf.ByteString getLocationBytes() {
				java.lang.Object ref = location_;
				if (ref instanceof String) {
					com.google.protobuf.ByteString b = com.google.protobuf.ByteString
							.copyFromUtf8((java.lang.String) ref);
					location_ = b;
					return b;
				} else {
					return (com.google.protobuf.ByteString) ref;
				}
			}

			/**
			 * <code>string location = 14;</code>
			 */
			public Builder setLocation(java.lang.String value) {
				if (value == null) {
					throw new NullPointerException();
				}

				location_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>string location = 14;</code>
			 */
			public Builder clearLocation() {

				location_ = getDefaultInstance().getLocation();
				onChanged();
				return this;
			}

			/**
			 * <code>string location = 14;</code>
			 */
			public Builder setLocationBytes(com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				checkByteStringIsUtf8(value);

				location_ = value;
				onChanged();
				return this;
			}

			private java.lang.Object state_ = "";

			/**
			 * <code>string state = 15;</code>
			 */
			public java.lang.String getState() {
				java.lang.Object ref = state_;
				if (!(ref instanceof java.lang.String)) {
					com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
					java.lang.String s = bs.toStringUtf8();
					state_ = s;
					return s;
				} else {
					return (java.lang.String) ref;
				}
			}

			/**
			 * <code>string state = 15;</code>
			 */
			public com.google.protobuf.ByteString getStateBytes() {
				java.lang.Object ref = state_;
				if (ref instanceof String) {
					com.google.protobuf.ByteString b = com.google.protobuf.ByteString
							.copyFromUtf8((java.lang.String) ref);
					state_ = b;
					return b;
				} else {
					return (com.google.protobuf.ByteString) ref;
				}
			}

			/**
			 * <code>string state = 15;</code>
			 */
			public Builder setState(java.lang.String value) {
				if (value == null) {
					throw new NullPointerException();
				}

				state_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>string state = 15;</code>
			 */
			public Builder clearState() {

				state_ = getDefaultInstance().getState();
				onChanged();
				return this;
			}

			/**
			 * <code>string state = 15;</code>
			 */
			public Builder setStateBytes(com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				checkByteStringIsUtf8(value);

				state_ = value;
				onChanged();
				return this;
			}

			public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
				return super.setUnknownFieldsProto3(unknownFields);
			}

			public final Builder mergeUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
				return super.mergeUnknownFields(unknownFields);
			}

			// @@protoc_insertion_point(builder_scope:com.farsunset.lvxin.model.proto.Model)
		}

		// @@protoc_insertion_point(class_scope:com.farsunset.lvxin.model.proto.Model)
		private static final com.farsunset.lvxin.model.proto.UserProto.Model DEFAULT_INSTANCE;
		static {
			DEFAULT_INSTANCE = new com.farsunset.lvxin.model.proto.UserProto.Model();
		}

		static com.farsunset.lvxin.model.proto.UserProto.Model getDefaultInstance() {
			return DEFAULT_INSTANCE;
		}

		private static final com.google.protobuf.Parser<Model> PARSER = new com.google.protobuf.AbstractParser<Model>() {
			public Model parsePartialFrom(com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws com.google.protobuf.InvalidProtocolBufferException {
				return new Model(input, extensionRegistry);
			}
		};

		public static com.google.protobuf.Parser<Model> parser() {
			return PARSER;
		}

		@java.lang.Override
		public com.google.protobuf.Parser<Model> getParserForType() {
			return PARSER;
		}

		public com.farsunset.lvxin.model.proto.UserProto.Model getDefaultInstanceForType() {
			return DEFAULT_INSTANCE;
		}

	}

	private static final com.google.protobuf.Descriptors.Descriptor internal_static_com_farsunset_lvxin_model_proto_Model_descriptor;
	private static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_com_farsunset_lvxin_model_proto_Model_fieldAccessorTable;

	private static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
		return descriptor;
	}

	private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
	static {
		java.lang.String[] descriptorData = { "\n\nUser.proto\022\037com.farsunset.lvxin.model."
				+ "proto\"\200\002\n\005Model\022\017\n\007account\030\001 \001(\t\022\020\n\010pass"
				+ "word\030\002 \001(\t\022\014\n\004name\030\003 \001(\t\022\021\n\ttelephone\030\004 "
				+ "\001(\t\022\r\n\005email\030\005 \001(\t\022\017\n\007orgCode\030\006 \001(\t\022\016\n\006g"
				+ "ender\030\007 \001(\t\022\r\n\005grade\030\010 \001(\005\022\017\n\007feature\030\t "
				+ "\001(\t\022\r\n\005motto\030\n \001(\t\022\016\n\006online\030\013 \001(\t\022\021\n\tlo"
				+ "ngitude\030\014 \001(\001\022\020\n\010latitude\030\r \001(\001\022\020\n\010locat"
				+ "ion\030\016 \001(\t\022\r\n\005state\030\017 \001(\tB\013B\tUserProtob\006p" + "roto3" };
		com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner = new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
			public com.google.protobuf.ExtensionRegistry assignDescriptors(
					com.google.protobuf.Descriptors.FileDescriptor root) {
				descriptor = root;
				return null;
			}
		};
		com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(descriptorData,
				new com.google.protobuf.Descriptors.FileDescriptor[] {}, assigner);
		internal_static_com_farsunset_lvxin_model_proto_Model_descriptor = getDescriptor().getMessageTypes().get(0);
		internal_static_com_farsunset_lvxin_model_proto_Model_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
				internal_static_com_farsunset_lvxin_model_proto_Model_descriptor,
				new java.lang.String[] { "Account", "Password", "Name", "Telephone", "Email", "OrgCode", "Gender",
						"Grade", "Feature", "Motto", "Online", "Longitude", "Latitude", "Location", "State", });
	}

	// @@protoc_insertion_point(outer_class_scope)
}
